import { Router } from 'express';
import authRoutes from './authRoutes.js';
import customerRoutes from './customerRoutes.js';
import locationRoutes from './locationRoutes.js';
import machineRoutes from './machineRoutes.js';
import routeRoutes from './routeRoutes.js';
import userRoutes from './userRoutes.js';
import reportRoutes from './reportRoutes.js';
import vehicleRoutes from './vehicleRoutes.js';
import stopRoutes from './stopRoutes.js';
import notificationRoutes from './notificationRoutes.js';
import settingsRoutes from './settingsRoutes.js';
import attendanceRoutes from './attendanceRoutes.js';
import inventoryRoutes from './inventoryRoutes.js';
import uploadRoutes from './uploadRoutes.js';
import analyticsRoutes from './analyticsRoutes.js';
import syncRoutes from './syncRoutes.js';
const apiRouter = Router();

apiRouter.use('/auth', authRoutes);
apiRouter.use('/customers', customerRoutes);
apiRouter.use('/locations', locationRoutes);
apiRouter.use('/machines', machineRoutes);
apiRouter.use('/routes', routeRoutes);
apiRouter.use('/users', userRoutes);
apiRouter.use('/reports', reportRoutes);
apiRouter.use('/vehicles', vehicleRoutes);
apiRouter.use('/stops', stopRoutes);
apiRouter.use('/notifications', notificationRoutes);
apiRouter.use('/settings', settingsRoutes);
apiRouter.use('/attendance', attendanceRoutes);
apiRouter.use('/inventory', inventoryRoutes);
apiRouter.use('/upload', uploadRoutes);
apiRouter.use('/analytics', analyticsRoutes);
apiRouter.use('/sync', syncRoutes);
export default apiRouter;
